version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-service
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5679/
    volumes:
      - ./n8n:/home/node/.n8n
      - ./data/invoices:/home/node/.n8n-files/invoices
      - ./configs:/home/node/.n8n-files/configs
      - ./data/outputs:/home/node/.n8n-files/outputs
      - ./data:/data
      - ./configs:/configs
    depends_on:
      python:
        condition: service_healthy
    networks:
      - n8n-network

  python:
    build: ./python
    container_name: python-service
    volumes:
      - ./configs:/configs
      - ./data:/data
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/list-invoices || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge